const AddRestaurantConstants = {
  CHANGE_VALUE: 'ADD_RESTAURANT_CONSTANTS.CHANGE_VALUE',
  ADD_RESTAURANT: 'ADD_RESTAURANT_CONSTANTS.ADD_RESTAURANT',
  CLEAR_STATE: 'ADD_RESTAURANT_CONSTANTS.CLEAR_STATE'
};

export { AddRestaurantConstants}
