const AppActionsConstants = {
  SET_REQUIRE_AUTH: 'APP_CONSTANTS.SET_REQUIRE_AUTH',
  SET_USERNAME_AUTH: 'APP_CONSTANTS.SET_USERNAME_AUTH',
  LOAD_USERNAME_AUTH: 'APP_CONSTANTS.LOAD_USERNAME_AUTH',
  LOGOUT: 'APP_CONSTANTS.LOGOUT'
};

export {AppActionsConstants}
