const RestaurantConstants = {
  CHANGE_VALUE: 'RESTAURANT_CONSTANTS.CHANGE_VALUE',
  LOAD_RESTAURANT: 'RESTAURANT_CONSTANTS.LOAD_RESTAURANT',
  SET_RESTAURANT_NAME: 'RESTAURANT_CONSTANTS.SET_RESTAURANT_NAME',
  SET_RESTAURANT_LOCATION: 'RESTAURANT_CONSTANTS.SET_RESTAURANT_LOCATION',
  HIDE_ADD_REVIEW: 'RESTAURANT_CONSTANTS.HIDE_ADD_REVIEW',
  SHOW_ADD_REVIEW: 'RESTAURANT_CONSTANTS.SHOW_ADD_REVIEW',
  SORT_REVIEWS: 'RESTAURANT_CONSTANTS.SORT_REVIEWS'
};

export { RestaurantConstants}
