const RestaurantsConstants = {
  SHOW_ADD_RESTAURANT: 'RESTAURANT_CONSTANTS.SHOW_ADD_RESTAURANT',
  HIDE_ADD_RESTAURANT: 'RESTAURANT_CONSTANTS.HIDE_ADD_RESTAURANT',
  SET_ADVANCED_SEARCH: 'RESTAURANT_CONSTANTS.SET_ADVANCED_SEARCH',
  SET_BASIC_SEARCH: 'RESTAURANT_CONSTANTS.SET_BASIC_SEARCH',
  LOAD_ALL_RESTAURANTS: 'RESTAURANT_CONSTANTS.LOAD_ALL_RESTAURANTS',
  SET_RESTAURANT_LIST: 'RESTAURANT_CONSTANTS.SET_RESTAURANT_LIST',
  CHANGE_VALUE: 'RESTAURANT_CONSTANTS.CHANGE_VALUE',
  BASIC_SEARCH: 'RESTAURANT_CONSTANTS.BASIC_SEARCH',
  ADVANCED_SEARCH: 'RESTAURANT_CONSTANTS.ADVANCED_SEARCH',
  SORT_RESTAURANTS: 'RESTAURANT_CONSTANTS.SORT_RESTAURANTS'
};

export {RestaurantsConstants}
