const ReviewConstants = {
  CHANGE_VALUE: 'REVIEW_CONSTANTS.CHANGE_VALUE',
  ADD_REVIEW: 'REVIEW_CONSTANTS.ADD_REVIEW',
  CLEAR_STATE: 'REVIEW_CONSTANTS.CLEAR_STATE',
  EDIT_REVIEW: 'REVIEW_CONSTANTS.EDIT_REVIEW',
  OPEN_STATE: {
    NEW: 0,
    EDIT: 1,
  }
};

export { ReviewConstants }
