const ProfileConstants = {
  CHANGE_VALUE: 'PROFILE_CONSTANTS.CHANGE_VALUE',
  LOAD_USER_DATA: 'PROFILE_CONSTANTS.LOAD_USER_DATA',
  DELETE_REVIEW: 'PROFILE_CONSTANTS.DELETE_REVIEW',
  UPDATE_NAME: 'PROFILE_CONSTANTS.UPDATE_NAME',
  UPDATE_LOCATION: 'PROFILE_CONSTANTS.UPDATE_LOCATION',
  CHECK_USER_EXISTS: 'PROFILE_CONSTANTS.CHECK_USER_EXISTS'
};

export {ProfileConstants}
