const LoginActionsConstants = {
  CHANGE_VALUE: 'LOGIN_CONSTANTS.CHANGE_VALUE',
  SET_LOGIN_COMPLETE: 'LOGIN_CONSTANTS.SET_LOGIN_COMPLETE',
  SET_LOGIN_FAILED: 'LOGIN_CONSTANTS.SET_LOGIN_FAILED',
  LOGIN_USER: 'LOGIN_CONSTANTS.LOGIN_USER',
};

export {LoginActionsConstants}
