const RegisterActionsConstants = {
  CHANGE_VALUE: 'REGISTER_CONSTANTS.CHANGE_VALUE',
  CHECK_USER_EXISTS: 'REGISTER_CONSTANTS.CHECK_USER_EXISTS',
  SET_USER_TAKEN: 'REGISTER_CONSTANTS.SET_USER_TAKEN',
  SET_USER_FREE: 'REGISTER_CONSTANTS.SET_USER_FREE',
  SET_REGISTRATION_COMPLETE: 'REGISTER_CONSTANTS.SET_REGISTRATION_COMPLETE',
  SET_REGISTRATION_FAILED: 'REGISTER_CONSTANTS.SET_REGISTRATION_FAILED',
  REGISTER_USER: 'REGISTER_CONSTANTS.REGISTER_USER',
  LOAD_COUNTRIES: 'REGISTER_CONSTANTS.LOAD_COUNTRIES',
  SET_COUNTRIES: 'REGISTER_CONSTANTS.SET_COUNTRIES'
};

export {RegisterActionsConstants}
